# Generated by Django 4.2.7 on 2026-01-20 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5)),
                ('component_type', models.CharField(choices=[('WHOLE_BLOOD', 'Whole Blood'), ('RBC', 'Red Blood Cells'), ('PLASMA', 'Plasma'), ('PLATELETS', 'Platelets'), ('CRYOPRECIPITATE', 'Cryoprecipitate')], max_length=20)),
                ('quantity', models.IntegerField(help_text='Quantity in units')),
                ('unit_volume', models.FloatField(default=450, help_text='Volume per unit in ml')),
                ('collection_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('storage_temperature', models.FloatField(help_text='Storage temperature in Celsius')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('USED', 'Used'), ('EXPIRED', 'Expired'), ('TESTING', 'Testing')], default='AVAILABLE', max_length=20)),
                ('batch_number', models.CharField(max_length=100, unique=True)),
                ('test_results', models.FileField(blank=True, null=True, upload_to='test_results/')),
                ('is_tested', models.BooleanField(default=False)),
                ('test_date', models.DateField(blank=True, null=True)),
                ('storage_location', models.CharField(help_text='Specific storage location in facility', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blood_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_inventory', to=settings.AUTH_USER_MODEL)),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blood Inventory',
                'verbose_name_plural': 'Blood Inventory',
                'ordering': ['expiry_date', 'blood_group'],
            },
        ),
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5)),
                ('component_type', models.CharField(choices=[('WHOLE_BLOOD', 'Whole Blood'), ('RBC', 'Red Blood Cells'), ('PLASMA', 'Plasma'), ('PLATELETS', 'Platelets'), ('CRYOPRECIPITATE', 'Cryoprecipitate')], max_length=20)),
                ('quantity_required', models.IntegerField()),
                ('urgency', models.CharField(choices=[('LOW', 'Low Priority'), ('MEDIUM', 'Medium Priority'), ('HIGH', 'High Priority'), ('CRITICAL', 'Critical Emergency')], default='MEDIUM', max_length=20)),
                ('patient_details', models.TextField(blank=True)),
                ('purpose', models.CharField(blank=True, max_length=255)),
                ('required_by', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('FULFILLED', 'Fulfilled'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('fulfilled_quantity', models.IntegerField(default=0)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('suggested_blood_banks', models.JSONField(blank=True, default=list)),
                ('ai_confidence_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fulfilled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_requests', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
