# Generated by Django 4.2.7 on 2026-01-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIPredictiveModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('model_type', models.CharField(choices=[('STOCK_PREDICTION', 'Stock Prediction'), ('DEMAND_FORECAST', 'Demand Forecast'), ('EXPIRY_PREDICTION', 'Expiry Prediction'), ('DONOR_MATCHING', 'Donor Matching')], max_length=50)),
                ('model_version', models.CharField(max_length=50)),
                ('accuracy', models.FloatField(default=0.0)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
                ('model_path', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'AI Model',
                'verbose_name_plural': 'AI Models',
            },
        ),
    ]
